version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"

    env_file:
      - ./variables.txt
