version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - variables.txt
    depends_on:
      - api

  api:
    build:
      context: ./api
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - variables.txt
